# **Statistika Deskriptif Untuk Data Science**

Statistika deskriptif berkaitan dengan bagaimana kita
menjelaskan dan murumuskan suatu data. Umumnya digunakan dua metode pendekatan:

1. **Pendekatan kuantitatif** menjelaskan data secara numerik.

2. **Pendekatan visual** mengilustrasikan data menggunakan chart, plot, histogram, atau grafik lainnya.

Kita dapat menerapkan statistika deskriptif ke dalam satu atau banyak data. Ketika kita menjelaskan dan merumuskan suatu data tunggal, maka kita sedang melakukan **analisa univariate**. Ketika kita mencari hubungan statistika antara sepasang data, maka kita sedang melakukan **analisa bivariate**. Begitu juga dengan ** analisa multivariate** yang berarti kita menerapkannya pada banyak data sekaligus.

## **Populasi dan Sampel**

Dalam statistika, **populasi** merupakan sekumpulan elemen atau sesuatu yang ingin di amati, namun cakupan populasi biasa sangat besar sehingga akan sangat sulit untuk megumpulkan dan menganalisa datanya. Itulah mengapa ahli statistik biasanya mencoba mengambil kesimpulan mengenai suatu populasi dengan menguji dan memilih perwakilan dari populasi tersebut. Perwakilan dari populasi ini yang biasa kita sebut **sampel**. Secara ideal, sampel harus memiliki komponen penting statistik dari suatu populasi agar dapat mengggambarkan populasi secara nyata.

## **Outliers (pencilan)**

Outlier merupakan sebuah data point yang jauh berbeda dengan mayoritas data pada suatu sampel atau populasi. Beberapa penyebab adanya outlier dalam data kita diantaranya:

* **Variasi alami** dalam suatu data

* **Change** atau perubahan perilaku pada sistem yang kita
observasi

* **Error** atau kesalahan saat pengumpulan data

Kesalahan saat pengumpulan data biasanya menjadi penyebab yang paling umum adanya outlier.

## **Jenis-jenis ukuran data**

**Central tendency** (ukuran pemusatan data), biasanya kita lebih mengenal central tendency dengan Mean, Median, dan Modus. Salah satu hasil yang didapat dari pengukuran 3M ini adalah Skewness, yang nantinya kita bias tahu dimana data terkonsentrasi dan dimana letak outlier(pencilan) pada data tersebut. Negative skewed memiliki arti bahwa data terkonsentrasi di atas rata-rata dan outliernya berada pada data di bawah rata-rata, dapat dilihat bahwa pada kondis ini nilai mean lebih kecil dari median. Positif skew memiliki arti yang berkebalikan dengan negatif skew. Sedangkan jika nilai 3M-nya sama, maka data tersebut memiliki normal skew yang akan membentuk distribusi simetris.

**Variability** (ukuran sebaran data), cara yang paling umum untuk mengetahui ukuran sebaran data adalah dengan mengukur nilai range, interquartile range(IQR), variansi, kovariansi, dan standar deviasi dari data tersebut. **Variansi** adalah nilai ‘average’ dari kuadrat antara simpangan(deviasi) dengan rata-rata populasi. Bingung? Sama hehe. Mari kita lihat rumusan untuk menghitung variansi populasi berikut.

Missalkan X adalah variabel random dengan distribusi peluang f(x) dan rata-rata **μ**. Maka variansi dari X adalah:

Interpretasi dari rumusan di atas adalah nilai **σ^2** akan lebih kecil untuk kelompok nilai x yang dekat dengan *μ* dibandingkan dengan kelompok nilai x yang jauh dari **μ**. Dengan kata lain, jika nilai-nilai x cenderung terkonsentrasi di dekat rataannya, maka variansinya kecil, sedangkan jika jauh dari rataannya maka variansinya besar. Dapat dilihat pada gambar berikut:

Pada kenyataannya, kita jarang sekali dapat mengukur seluruh populasi, yang bisa kita ukur hanya sampel, misalnya kita bisa saja mengukur tinggi badan peserta training data science, tapi kita tidak dapat mengukur tinggi badan seluruh manusia di bumi, hal ini akan mengakibatkan bias terhadap pengukuran yang dilakukan, oleh karena itu, agar tidak bias dalam mengukur nilai varian, maka N sebagai pembagi penjumlahan kuadrat (sum of squares) diganti dengan N-1 (degree of freedom). Rumusan varian sampel menjadi:

Akar kuadrat dari variansi ini merupakan nilai dari **standar deviasi** (simpangan baku). Jika kita memili dua variabel random X dan Y, nilai **kovariansi** menunjukkan hubungan antara kedua variabel tersebut.

Jika kedua variabel tersebut bergerak ke arah yang sama (X membesar dan Y membesar) maka hasil kali (X – μX)(Y – μY) cenderung bernilai positif, sebaliknya jika kedua variabel bergerak ke arah berlawanan (X membesar dan Y mengecil), maka hasil kali (X – μX)(Y – μY)akan cenderung bernilai negatif. Tanda kovariansi (+ atau -) menunjukkan apakah hubungan antara kedua variabel positif atau negatif. Jika kovariansi bernilai positif maka ada hubungan antara dua variabel tersebut dan berbanding lurus, jika kovariansi bernilai negatif hubungannya berbanding terbalik, sedangkan jika bernilai nol maka tidak ada hubungan antara dua variabel tersebut.

**Correlation coefficient** atau hubungan variability menyatakan seberapa kuat hubungan antara dua variabel, koefisien korelasi dapat dihitung menggunakan persamaan:


Nilai koefisien korelasi berkisar antara (-1) hingga (+1) bergantung pada nilai kovariansinya. Jika nilai koefisien korelasi mendekati -1 atau mendekati +1 maka X dan y memiliki korelasi linier yang tinggi, jika nilai koefisien korelasinya -1 atau +1 kedua variabel tersebut memiliki korelasi sempurna, sedangkan jika nilai koefisien korelasinya nol maka X dan y tidak memiliki hubungan.

Library statistika pada python yang biasa digunakan yaitu:

* **statistics**, merupakan built-in library pada python untuk statistika deskriptif. Kita dapat menggunakannya jika dataset yang kita miliki tidak terlalu besar, atau ketika kita tidak dapat meng-import library yang lain.

* **NumPy** merupakan library pihak ketiga yang digunakan untuk perhitungan numerik, sangat baik untuk digunakan pada array tunggal atau multidimensi.

* **SciPy** merupakan library pihak ketiga yang digunakan untuk perhitungan scientific. Dibuat dengan dasar library NumPy namun memiliki fungsi tambahan termasuk di dalamnya scipy.stats untuk analisa statistik.

* **Pandas** merupakan library pihak ketiga untuk perhitungan numerik, pandas juga dibuat dengan dasar library NumPy. Sangat berguna untuk mengolah data 1D menggunakan objek Series, dan data 2D menggunakan objek DataFrame.

# **Menghitung statistika deskriptif menggunakan python**

Kita hanya akan menggunakan library statistics, NumPy, dan SciPy untuk menghitung nilai-nilai yang dihasilkan dari statistika deskriptif, library Pandas akan dipelajari pekan depan. Kita mulai dengan meng-import librarynya:

In [ ]:
import math
import statistics
import numpy as np
import scipy.stats

Kita buat suatu data berupa python list yang berisi data numerik secara random:

In [ ]:
x = [8.0, 1, 2.5, 4, 28.0]
x_dgn_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]

In [ ]:
x

[8.0, 1, 2.5, 4, 28.0]

In [ ]:
x_dgn_nan

[8.0, 1, 2.5, nan, 4, 28.0]

Sekarang kita punya dua list, x dan x_dgn_nan, keduanya hampir sama, bedanya yaitu x_dgn_nan memiliki nilai nan (not a number). Sangat penting bagaimana python menghadapi nilai nan ini. Dalam data science, missing value sangat sering terjadi, dan biasanya nilai yang hilang ini diganti dengan nan. Sekarang kita coba buat np.ndarray objek dari variabel x dan x_dgn_nan:

In [ ]:
y, y_dgn_nan = np.array(x), np.array(x_dgn_nan)

In [ ]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [ ]:
y_dgn_nan

array([ 8. ,  1. ,  2.5,  nan,  4. , 28. ])

# **Menghitung Ukuran Pemusatan Data**

Kita akan nenpelajari bagaimana menghitung ukuran pemusatan data ini menggunakna python.

**Mean** (rataan) Kita dapat menghitung mean hanya dengan python tanpa meng-import library apapun menggunakan sum() dan len():

In [ ]:
mean_ = sum(x) / len(x)
mean_

8.7

Kita juga bisa menggunakan fungsi bawaan dari library statistics python:

In [ ]:
mean_ = statistics.mean(x)
mean_

8.7

In [ ]:
# mean_ = statistics.fmean(x)
# mean_

Fungsi fmean() mulai dikenalkan pada python 3.8 sebagai alternatif untuk perhitungan yang lebih cepat dan selalu menghasilkan nilai float. Namun, fungsi mean() dan fmean() akan menghasilkan nilai nan jika di dalam variabel yang dihitungnya berisi nilai nan:

In [ ]:
mean_ = statistics.mean(x_dgn_nan)
mean_

nan

In [ ]:
# mean_nan = statistics.fmean(x_dgn_nan)
# mean_nan 

Jika kita ingin mengabaikan nilai nan yang ada pada variabel tersebut maka dapat menggunakan np.nanmean():

In [ ]:
np.nanmean(y_dgn_nan)

8.7

**Weighted Mean** atau rataan berbobot merupakan generalisasi dari rataan aritmatika sehingga kita dapat menentukan kontribusi relatif (bobot) dari setiap data point untuk penghitungan hasilnya. Kita dapat menghitung weighted mean menggunakan python dengan menggabungkan antara sum() dengan range() atau zip() seperti pada contoh berikut:

In [ ]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]
wmean = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean

6.95

In [ ]:
wmean = sum(x_ * w_ for (x_, w_) in zip(x, w)) / sum(w)
wmean

6.95

Tetapi jika kita memiliki dataset yang cukup besar maka NumPy memberikan soolusi yang lebih baik untuk penghitungan weighted mean ini menggunakan np.average():

In [ ]:
y, w = np.array(x), np.array(w)
wmean = np.average(y, weights=w)
wmean

6.95

Hati-hati ketika melakukan perhitungan untuk data berisi nilai nan.

In [ ]:
w = np.array([0.1, 0.2, 0.3, 0.0, 0.2, 0.1])
np.average(y_dgn_nan, weights=w)

nan

**Harmonic Mean** atau rataan harmonis dapat dirumuskan dengan 𝑛/Σᵢ(1/𝑥ᵢ) dimana i=1, 2, …, n dan n adalah jumlah data point pada dataset x. Kita bisa menghitungnya menggunakan python:

In [ ]:
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

Kita juga bisa menggunakan statistics.harmonic_mean():

In [ ]:
hmean = statistics.harmonic_mean(x)
hmean

2.7613412228796843

Jika terdapat nilai nan, maka statistics.harmonic_mean() akan menghasilkan nilai nan, dan jika terdapat nilai negatif, maka akan terjadi error dalam perhitungannya:

In [ ]:
statistics.harmonic_mean(x_dgn_nan)

nan

In [ ]:
statistics.harmonic_mean([1, 0, 2])

0

In [ ]:
# statistics.harmonic_mean([1, 2, -2])  #StatisticsError : harmonic mean does not support negative values

Cara ketiga adalah dengan menggunakan scipy.stats.hmean():

In [ ]:
scipy.stats.hmean(y)

2.7613412228796843

**Geometric Mean** atau rataan geometris merupakan akar pangkat-n dari seluruh hasil perkalian elemen 𝑥ᵢ sejumlah n pada dataset x, dapat dirumuskan dengan ⁿ√(Πᵢ𝑥ᵢ), dimana dimana i=1, 2, …, n dan n adalah jumlah data point pada dataset x. Kita dapat menggunakan python untuk menghitung nilai rataan geometris ini sebagai berikut:

In [ ]:
gmean = 1
for item in x:
    gmean *= item

gmean **= 1 / len(x)
gmean

4.677885674856041

Pada python 3.8 kita dapat menggunakan statistics.geometric_mean(), yang akan mengubah semua nilai pada dataset menjadi float kemudian menghitung rataan geometrisnya:

In [ ]:
!apt-get install python3.8

Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3.8 is already the newest version (3.8.8-1+bionic2).
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.


In [ ]:
# gmean = statistics.geometric_mean(x)
# gmean

Dengan menggunakan scipy.stats.gmean():

In [ ]:
scipy.stats.gmean(y)

4.67788567485604

Jika terdapat nilai nan pada dataset maka gmean() akan menghasilkan nan. Jika terdapat satu saja nilai 0, maka akan menghasilkan rataan geometris 0 disertai peringatan.

**Median** suatu sampel merupakan nilai tengah dari dataset yang telah diurutkan. Dataset tersebut dapat diurutkan secara naik atau turun. Jika jumlah elemen n dari dataset adalah ganjil maka median adalah elemen pada posisi 0.5(n+1). Jika n genap, maka mediannya adalah rataan aritmatika dari dua nilai tengah, yaitu yang berada pada posisi 0.5n dan 0.5n+1. Perbedaan utama antara sifat mean dan median dari suatu dataset adalah hubungannya dengan outlier pada dataset tersebut. Nilai mean sangat dipengaruhi oleh outlier sedangkan nilai median hampir tidak dipengaruhi atau bahkan tidak dipengaruhi sama sekali. Perhatikan gambar berikut:

Dataset bagian atas memiliki nilai 1, 2.5, 4, 8, dan 28. Nilai mean dari dataset tersebut adalah 8.7 dan nilai mediannya adalah 4. Dataset bagian bawah menunjukkan bagaimana perubahan nilai mean ketika nilai paling kanan pada dataset atas yang memiliki nilai 28 di pindahkan.

Berikut adalah salah satu cara mencari nilai median menggunakan python:


In [ ]:
n = len(x)
if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord, index = sorted(x), round(0.5 * n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
median_

4

Langkah penting pada proses di atas adalah:

Mengurutkan elemen-elemen pada dataset
Mencari elemen tengah pada dataset yang telah diurutkan
Kita juga bisa mendapatkan nilai median dengan statistics.median():

In [ ]:
median_ = statistics.median(x)
median_

4

Cara yang lain untuk mendapatkan nilai median adalah menggunakan np.median():

In [ ]:
median_ = np.median(y)
median_

4.0

**Mode** atau modus dari suatu sampel dataset adalah nilai yang paling banyak muncul dalam dataset tersebut. Dengan python kita dapat menghasilkan nilai modus suatu dataset sebagai berikut:

In [ ]:
u = [2, 3, 2, 8, 12]
mode_ = max((u.count(item), item) for item in set(u))[1]
mode_

2

Kita dapat mencari modus dari suatu daset menggunakan statistics.mode(), dan juga menggunakan statistics.multimode() (mulai dikenalkan pada python 3.8) jika nilai modusnya tidak hanya satu:

In [ ]:
mode_ = statistics.mode(u)
mode_

2

In [ ]:
# mode_ = statistics.multimode(u)
# mode_

Dapat dilihat bahwa mode() menghasilkan nilai tunggal, sedangkan multimode() menghasilkan list yang berisi nilai modus. Bahkan mode() akan menghasilkan error jika dalam dataset tersebut terdapat dua modus:

In [ ]:
# v = [12, 15, 12, 15, 21, 15, 12]
# statistics.mode(v)  # StatisticsError
# statistics.multimode(v)

Bagaimana jika dalam dataset terdapat nilai nan? Bisa dicoba sendiri hehe..

Untuk menghasilkan nilai modus jika menggunakan scipy.stats.mode():


In [ ]:
u, v = np.array(u), np.array(v)
mode_ = scipy.stats.mode(u)
mode_

ModeResult(mode=array([2]), count=array([2]))

In [ ]:
mode_ = scipy.stats.mode(v)
mode_

ModeResult(mode=array([12]), count=array([3]))

Jika terdapat lebih dari satu nilai modus, scipy.stats.mode() akan menjadikan nilai terkecil sebagai modus.

# **Menghitung Ukuran Sebaran Data**

Ukuran pemusatan saja tidak cukup untuk menjelaskan suatu data, kita juga perlu menghitung ukuran sebaran data. Beberapa ukuran sebaran data yang perlu diketahui yaitu:

**Variance** atau variansi. Menghitung variansi menggunakan python dapat dilakukan dengan cara berikut:

In [ ]:
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
var_

123.19999999999999

Cara yang lebih singkat dan elegan adalah menggunakan statistics.variance():

In [ ]:
var_ = statistics.variance(x)
var_

123.2

Bagaimana jika terdapat nilai nan dalam dataset? Silahkan dicoba sendiri hehe..

Cara yang lain yaitu menggunakan fungsi np.var() atau metode .var():

In [ ]:
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [ ]:
var_ = y.var(ddof=1)
var_

123.19999999999999

Penting untuk mendefinisikan nilai ddof=1. Parameter ini digunakan agar perhitungan nilai s2 sesuai yaitu menggunakan n-1 sebagai pembagi bukan n saja. Untuk dataset yang memiliki nilai nan, kita dapat mengabaikan nilai nan tersebut dengan np.nanvar():

In [ ]:
np.nanvar(y_dgn_nan, ddof=1)

123.19999999999999

**Standar Deviasi** atau simpangan baku. Menghitung standar deviasi menggunakan python dapat dilakukan dengan cara:

In [ ]:
std_ = var_ ** 0.5
std_

11.099549540409285

Kita juga bisa menggunakan statistics.dev():

In [ ]:
std_ = statistics.stdev(x)
std_

11.099549540409287

Jika kita menggunakan Numpy, perhatikan untuk menggunakan fungsi yang sesuai jika terdapat nilai nan:

In [ ]:
np.std(y, ddof=1)


11.099549540409285

In [ ]:
y.std(ddof=1)


11.099549540409285

In [ ]:
np.std(y_dgn_nan, ddof=1)


nan

In [ ]:
y_dgn_nan.std(ddof=1)


nan

In [ ]:
np.nanstd(y_dgn_nan, ddof=1)


11.099549540409285

Skewness, nilai dari skewness dapat dihasilkan menggunakan python dengan cara:

In [ ]:
x = [8.0, 1, 2.5, 4, 28.0]
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
std_ = var_ ** 0.5
skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))
skew_

1.9470432273905929

Kita juga bisa menggunakan scipy.stats.skew():

In [ ]:
y, y_dgn_nan = np.array(x), np.array(x_dgn_nan)
scipy.stats.skew(y, bias=False)


1.9470432273905927

In [ ]:
scipy.stats.skew(y_dgn_nan, bias=False)


nan

suatu dataset dapat dianggap simetris jika memiliki nilai skewness mendekati 0, yaitu antara -0.5 dan 0.5.

Percentiles ke-p dari sekumpulan data adalah nilai dimana p% dari data tersebut berada dibawahnya. Setiap data memiliki tiga nilai kuartil, yang membagi data menjadi 4 bagian sama besar.

1. Kuartil pertama (Q1) adalah persentil ke-25 dari data
2. Kuartil kedua (Q2) adalah persentil ke-50 dari data yang juga merupakan median dari data tersebut.
3. Kuartil ketiga (Q3) adalah persentil ke-75 dari data

Nilai persentil dapat dicari menggunakan np.percentile():

In [ ]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
y = np.array(x)
np.percentile(y, 5)


-3.44

In [ ]:
np.percentile(y, 95)

34.919999999999995

Jika kita ingin mengabaikan nilai nan pada data maka digunakan np.nanpercentile():

In [ ]:
y_dgn_nan = np.insert(y, 2, np.nan)
y_dgn_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [ ]:
np.nanpercentile(y_dgn_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

**Ranges** dari data adalah selisih antara elemen maksimum dan elemen minimum pada suatu dataset. Kita dapat menghitungnya dengan fungsi np.ptp():

In [ ]:
np.ptp(y)


46.0

In [ ]:
np.ptp(y_dgn_nan)

nan

Alternatifnya, kita bisa menggunakan fungsi bawaan python dan NumPy:

In [ ]:
np.amax(y) - np.amin(y)


46.0

In [ ]:
np.nanmax(y_dgn_nan) - np.nanmin(y_dgn_nan)


46.0

In [ ]:
y.max() - y.min()

46.0

# **Menghitung Korelasi Antara Sepasang Data**

Korelasi atau hubungan antara sepasang data dapat dilihat dengan menghitung:

**Covariance**, dengan menggunakan fungsi dari python kovariansi dapat dihitung sebagai berikut:

In [ ]:
n = len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n - 1))
cov_xy

228.75194444444446

Dengan menggunakan np.cov() dari NumPy kita akan mendapatkan matriks kovariansi:

In [ ]:
# cov_matrix = np.cov(x_, y_)
# cov_matrix

Dimana nilai 38.5 atau posisi atas kiri merupakan nilai variansi dari x, dan nilai 13.91 merupakan nilai variansi dari y, dan dua nilai lainnya merupakan nilai kovariansi antara x dan y, yaitu 19.95.

**Correlation coefficient**, untuk menghitung koefisien korelasi hanya menggunakan fungsi bawaan python adalah sebagai berikut:

In [ ]:
var_x = sum((item - mean_x)**2 for item in x) / (n - 1)
var_y = sum((item - mean_y)**2 for item in y) / (n - 1)
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

1.0

Library scipy.stats memiliki fungsi pearsonr() yang menghitung nilai dari koefisien korelasi dan juga nilai p-value nya:

In [ ]:
# r, p = scipy.stats.pearsonr(x_, y_)
# r

In [ ]:
# p

Jika ingin menggunakan NumPy, dapat memakai fungsi np.corrcoef() dengan argumen x_ dan y_, maka didapatkan matriks koefisien korelasinya:

In [ ]:
# corr_matrix = np.corrcoef(x_, y_)
# corr_matrix

Nilai 1 pada matriks tersebut menunjukkan koefisien korelasi antara satu argumen dengan dirinya sendiri, sedangkan dua nilai yang lain menunjukkan koefisien korelasi antara kedua argumen yakni x_ dan y_.

In [ ]:
# r = corr_matrix[0, 1]
# r

In [ ]:
# r = corr_matrix[1, 0]
# r

Kita juga bisa menggukanan fungsi scipy.stats.linregress() yang akan menghasilkan beberapa nilai, salah satunya adalah koefisien korelasinya:

In [ ]:
# scipy.stats.linregress(x_, y_)
# result = scipy.stats.linregress(x_, y_)
# r = result.rvalue
# r

https://www.academia.edu/25566517/Variansi_and_Kovariansi

https://realpython.com/python-statistics/


# Soal 1: Law of Large Numbers

Menurut Law of Large Numbers (LLN) jika kita mengulang suatu percobaan, semakin banyak kita mengulang maka rata-rata hasil yang di dapat akan mendekati apa yang kita perkirakan.

Sebagai caontoh, sebuah dadu dengan 6-sisi akan menghasilkan angka 1, 2, 3, 4, 5, atau 6 dengan probabilitas yang sama untuk masing-masing angkanya. Maka, perkiraan rata-rata hasil yang akan di dapat adalah (1+2+3+4+5+6)/6 = 3.5
Menurut LLN, semakin banyak kita mengocok dadu, maka rata-rata hasil yang didapatkan akan semakin mendekati nilai perkiraan rata-ratanya yaitu 3.5

Begitu juga jika kita memiliki sebuah dataset berisi angka-angka acak dengan nilai rata-rata(μ) = 0 dan standar deviasi(σ) = 1, maka angka-angka tersebut akan terdistribusi secara normal dengan semakin banyaknya isi dari dataset tersebut.

Dari gambar di atas, maka semakin banyaknya isi dari dataset, jumlah angka-angka pada dataset yang memiliki nilai -1 < angka < 1 akan semakin mendekati 68.2%.
Lengkapi code dibawah ini untuk membuktikan hal tersebut.


In [ ]:
import numpy as np
from numpy.random import randn

N = 20                     #Tentukan ukuran sampel
counter = 0               #Untuk mereset perhitungan

for item in randn(20) :               #Mulai iterasi dan tambahkan nilai counter jika memenuhi syarat

  if -1 < item < 1 :
    counter+=item


hasil = counter/N         #Hitung nilai persentase jumlahnya
print(hasil)

0.02172893179532513


---

# Soal 2: Menghitung nilai-nilai dari statistika deskriptif

In [ ]:
import statistics
import numpy as np
import scipy.stats

#Berikut adalah data dari breast cancer dataset, area dan status mematikan atau tidaknya

area = [1001. , 1326. , 1203. ,  386.1, 1297. ,  477.1, 1040. ,  577.9, 519.8,  475.9,  797.8,  781. , 1123. ,  782.7,  578.3,  658.8, 684.5,  798.8, 1260. ,  566.3,  520. ,  273.9,  704.4, 1404. ,
        904.6,  912.7,  644.8, 1094. ,  732.4,  955.1, 1088. ,  440.6, 899.3, 1162. ,  807.2,  869.5,  633. ,  523.8,  698.8,  559.2, 563. ,  371.1, 1104. ,  545.2,  531.5, 1076. ,  201.9,  534.6,
        449.3,  561. ,  427.9,  571.8,  437.6, 1033. ,  712.8,  409. , 1152. ,  656.9,  527.2,  224.5,  311.9,  221.8,  645.7,  260.9, 499. ,  668.3,  269.4,  394.1,  250.5,  502.5, 1130. ,  244. ,
        929.4,  584.1,  470.9,  817.7,  559.2, 1006. , 1245. ,  506.3, 401.5,  520. , 1878. , 1132. ,  443.3, 1075. ,  648.2, 1076. , 466.1,  651.9,  662.7,  728.2,  551.7,  555.1,  705.6, 1264. ,
        451.1,  294.5,  412.6,  642.5,  582.7,  143.5,  458.7,  298.3, 336.1,  530.2,  412.5,  466.7, 1509. ,  396.5,  290.2,  480.4, 629.9,  334.2,  230.9,  438.6,  245.2,  682.5,  782.6,  982. ,
        403.3, 1077. , 1761. ,  640.7,  553.5,  588.7,  572.6, 1138. , 674.5, 1192. ,  455.8,  748.9,  809.8,  761.7, 1075. ,  506.3, 423.6,  399.8,  678.1,  384.8,  288.5,  813. ,  398. ,  512.2,
        355.3,  432.8,  432. ,  689.5,  640.1,  585. ,  519.4,  203.9, 300.2,  381.9,  538.9,  460.3,  963.7,  880.2,  448.6,  366.8, 419.8, 1157. , 1214. ,  464.5, 1686. ,  690.2,  357.6,  886.3,
        984.6,  685.9,  464.1,  565.4,  736.9,  372.7,  349.6,  227.2, 302.4,  832.9,  526.4,  508.8, 2250. , 1311. ,  766.6,  402. , 710.6,  317.5, 1041. ,  420.3,  428.9,  463.7,  609.9,  507.4,
        288.1,  477.4,  671.4,  516.4,  588.9, 1024. , 1148. ,  642.7, 461. ,  951.6, 1685. ,  597.8,  481.9,  716.6,  295.4,  904.3, 529.4,  725.5, 1290. ,  428. , 2499. ,  948. ,  610.7,  578.9,
        432.2,  321.2, 1230. , 1223. ,  568.9,  561.3,  313.1,  761.3, 546.4,  641.2,  329.6,  684.5,  496.4,  503.2,  895. ,  395.7, 386.8, 1319. ,  279.6,  603.4, 1670. , 1306. ,  623.9,  920.6,
        575.3,  476.5,  389.4,  590. , 1155. ,  337.7,  541.6,  512.2, 347. ,  406.3, 1364. ,  407.4, 1206. ,  928.2, 1169. ,  602.4, 1207. ,  713.3,  773.5,  744.9, 1288. ,  933.1,  947.8,  758.6,
        928.3, 1419. ,  346.4,  561. ,  512.2,  344.9,  632.6,  388. , 1491. ,  289.9,  998.9,  435.6,  396.6, 1102. ,  572.3,  587.4, 1138. ,  427.3, 1145. ,  805.1,  516.6,  489. ,  441. ,  515.9,
        394.1,  396. ,  651. ,  687.3,  513.7,  432.7,  492.1,  582.7, 363.7,  431.1,  633.1,  334.2, 1217. ,  471.3, 1247. ,  334.3, 403.1,  417.2,  537.3,  246.3,  566.2,  530.6,  418.7,  664.9,
        504.1,  409.1,  221.2,  481.6,  461.4, 1027. ,  244.5,  477.3, 324.2, 1274. ,  504.8, 1264. ,  457.9,  489.9,  616.5,  446. , 813.7,  826.8,  793.2,  514. ,  387.3,  390. ,  464.4,  918.6,
        514.3, 1092. ,  310.8, 1747. ,  641.2,  280.5,  373.9, 1194. , 420.3,  321.6,  445.3,  668.7,  402.7,  426.7,  421. ,  758.6, 2010. ,  716.6,  384.6,  485.8,  512. ,  593.7,  241. ,  278.6,
        491.9,  546.1,  496.6,  838.1,  552.4, 1293. , 1234. ,  458.4, 1546. , 1482. ,  840.4,  711.8, 1386. , 1335. ,  579.1,  788.5, 338.3,  562.1,  580.6,  361.6,  386.3,  372.7,  447.8,  462.9,
        541.8,  664.7,  462. ,  596.6,  392. , 1174. ,  321.6,  234.3, 744.7, 1407. ,  446.2,  609.1,  558.1,  508.3,  378.2,  431.9, 994. ,  442.7,  525.2,  507.6,  469.1,  370. ,  800. ,  514.5,
        991.7,  466.1,  399.8,  373.2,  268.8,  693.7,  719.5,  433.8, 271.2,  803.1,  495. ,  380.3,  409.7,  656.1,  408.2,  575.3, 289.7,  307.3,  333.6,  359.9,  381.1,  501.3,  685. ,  467.8,
       1250. , 1110. ,  673.7,  599.5,  509.2,  611.2,  592.6,  606.5, 371.5,  928.8,  585.9,  340.9,  990. ,  441.3,  981.6,  674.8, 659.7, 1384. ,  432. , 1191. ,  442.5,  644.2,  492.9,  557.2,
        415.1,  537.9,  520.2,  290.9,  930.9, 2501. ,  646.1,  412.7, 537.3,  542.9,  536.9,  286.3,  980.5,  408.8,  289.1,  449.9, 686.9,  465.4,  358.9,  506.9,  618.4,  599.4,  404.9,  815.8,
        455.3,  602.9,  546.3,  571.1,  747.2,  476.7,  666. , 1167. , 420.5,  857.6,  466.5,  992.1, 1007. ,  477.3,  538.7,  680.9, 485.6,  480.1, 1068. , 1320. ,  689.4,  595.9,  476.3, 1682. ,
        248.7,  272.5,  453.1,  366.5,  819.8,  731.3,  426. ,  680.7, 556.7,  658.8,  701.9,  391.2, 1052. , 1214. ,  493.1,  493.8, 257.8, 1841. ,  388.1,  571. ,  293.2,  221.3,  551.1,  468.5,
        594.2,  445.2,  422.9,  416.2,  575.5, 1299. ,  365.6, 1308. , 629.8,  406.4,  178.8,  170.4,  402.9,  656.4,  668.6,  538.4, 584.8,  573.2,  324.9,  320.8,  285.7,  361.6,  360.5,  378.4,
        507.9,  264. ,  514.3,  321.4,  311.7,  271.3,  657.1,  403.5, 600.4,  386. ,  716.9, 1347. , 1479. , 1261. ,  858.1, 1265. , 181. ]

malignant = [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 0., 1.]

In [ ]:
#Hitung nilai mean dari 'area' menggunakan python saja, kemudian menggunakan library yang telah di import

mean_python = sum(area)/len(area)
print(mean_python)

mean_statistics = statistics.mean(area)     #untuk python3.8
print(mean_statistics)

mean_numpy = np.mean(area)
print(mean_numpy)

#Hitung nilai harmonic mean menggunakan scipy
harmonicmean = scipy.stats.hmean(area)
print(harmonicmean)

654.8891036906857
654.8891036906854
654.8891036906855
519.0704649372796


Expected output:


```
654.8891036906857 
654.8891036906854 
654.8891036906855 
519.0704649372796 
```




In [ ]:
#Hitung median dari 'area' menggunakan python saja dan numpy
def median_list (inp_list) :
    n = len(inp_list)
    ordered_list = sorted(inp_list)

    if n % 2 == 0 :
      index = round(0.5 * n)
    else :
      index = round(0.5* n-1)
    
    return ordered_list[index]

median_python = median_list(area)
print(median_python)

median_numpy = np.median(area)
print(median_numpy)

551.1
551.1


Expected output:


```
551.1
551.1
```




In [ ]:
#Hitung Mode dari 'area' menggunakan scipy

mode_scipy = scipy.stats.mode(area)
print(mode_scipy)

ModeResult(mode=array([512.2]), count=array([3]))


Expected output:


```
ModeResult(mode=array([512.2]), count=array([3]))
```



In [ ]:
#Hitung variance dari 'area' menggunakan python saja, numpy, dan statistics

n = len(area)
mean = sum(area)/n
variance_python = sum((item - mean)**2 for item in area) / (n - 1)
print(variance_python)

variance_numpy = np.var(area, ddof=1)
print(variance_numpy)

variance_statistics = statistics.variance(area)
print(variance_statistics)

123843.55431768096
123843.55431768115
123843.55431768113


Expected output:


```
123843.55431768096
123843.55431768115
123843.55431768113
```



In [ ]:
#Hitung standar deviasi dari 'area' menggunakan python saja dan numpy
n = len(area)
mean = sum(area)/n
variance = sum((item - mean)**2 for item in area) / (n - 1)

std_python = variance ** 0.5
print(std_python)

std_numpy = np.std(area, ddof=1)
print(std_numpy)

351.9141291816527
351.914129181653


Expected output:


```
351.9141291816527
351.914129181653
```



In [ ]:
#Hitung skewness dari 'area' menggunakan python saja dan scipy
n = len(area)
mean = sum(area)/n
variance = sum((item - mean)**2 for item in area) / (n - 1)
std_python = variance ** 0.5

skew_python = (sum((item - mean)**3 for item in area) * n / ((n - 1) * (n - 2) *std_python**3))
print(skew_python)

skew_scipy = scipy.stats.skew(area, bias=False)
print(skew_scipy)

1.6457321756240448
1.6457321756240424


Expected output:


```
1.6457321756240448
1.6457321756240424
```



In [ ]:
#Hitung percentile ke 66 dan 88 dari 'area' menggunakan numpy

percentile66 = np.percentile(area, 66)
print(percentile66)

percentile88 = np.percentile(area, 88)
print(percentile88)

665.8679999999999
1131.6799999999998


Expected output:


```
665.8679999999999
1131.6799999999998
```



In [ ]:
#Hitung range dari 'area' menggunakan python saja dan numpy

range_python = max(area) - min(area)
print(range_python)

range_numpy = np.ptp(area)
print(range_python)

2357.5
2357.5


Expected output:


```
2357.5
2357.5
```



In [ ]:
#Hitung covariance dari 'area' dan 'malignant' menggunakan python saja dan numpy
n = len(area)
mean_area, mean_malignant = sum(area) / n, sum(malignant) / n

cov_python = (sum((area[k] - mean_area) * (malignant[k] - mean_malignant) for k in range(n)) / (n - 1))
print(cov_python)

cov_numpy = np.cov(area, malignant)
print(cov_numpy)

-120.73822186192733
[[ 1.23843554e+05 -1.20738222e+02]
 [-1.20738222e+02  2.34176589e-01]]


Expexted output:

```
-120.73822186192733
[[ 1.23843554e+05 -1.20738222e+02]
 [-1.20738222e+02  2.34176589e-01]]
```



In [ ]:
#Hitung correlation coefficient 'area' dan 'malignant' menggunakan python saja, numpy, dan scipy
n = len(area)
mean_area, mean_malignant = sum(area) / n, sum(malignant) / n
var_area = sum((item - mean_area)**2 for item in area) / (n - 1)
var_malignant = sum((item - mean_malignant)**2 for item in malignant) / (n - 1)
std_area, std_malignant = var_area ** 0.5, var_malignant ** 0.5
cov = (sum((area[k] - mean_area) * (malignant[k] - mean_malignant) for k in range(n)) / (n - 1))
r = cov / (std_area * std_malignant)

corr_python = r
print(corr_python)

corr_numpy = np.corrcoef(area, malignant)
print(corr_numpy)

corr_scipy = scipy.stats.pearsonr(area, malignant)[0]
print(corr_scipy)

-0.7089838365853909
[[ 1.         -0.70898384]
 [-0.70898384  1.        ]]
-0.7089838365853901


Expected output:

```
-0.7089838365853909
[[ 1.         -0.70898384]
 [-0.70898384  1.        ]]
-0.70898383658539
```



In [ ]:
#Hitung p-value dari 'area' dan 'malignant' menggunakan scipy pearsonr dan linregress

p_pearsonr = scipy.stats.pearsonr(area, malignant)[1]
print(p_pearsonr)

p_linregress = scipy.stats.linregress(area, malignant).pvalue
print(p_linregress)

4.734564310304755e-88
4.734564310310984e-88


Expected output:
```
4.734564310304486e-88
4.734564310310984e-88
```



Apa kesimpulan yang dapat diambil dari nilai koefisien korelasi antara 'area' dengan 'malignant'?

Jawab:

"*Koefisien korelasi adalah nilai yang menunjukan kuat/tidaknya hubungan linier antar dua variabel. Koefisien korelasi biasa dilambangkan dengan huruf r dimana nilai r dapat bervariasi dari -1 sampai +1. Nilai r yang mendekati -1 atau +1 menunjukan hubungan yang kuat antara dua variabel tersebut dan nilai r yang mendekati 0 mengindikasikan lemahnya hubungan antara dua variabel tersebut. Sedangkan tanda + (positif) dan  – (negatif) memberikan informasi mengenai arah hubungan antara dua variabel tersebut. Jika bernilai + (positif) maka kedua variabel tersebut memiliki hubungan yang searah. Dalam arti lain peningkatan X akan bersamaan dengan peningkatan Y dan begitu juga sebaliknya. Jika bernilai – (negatif) artinya korelasi antara kedua variabel tersebut bersifat berlawanan. Peningkatan nilai X akan dibarengi dengan penurunan Y.*"

dari sini dapat dilihat dengan nilai korelasi -0.7089838365853909, atau mendekati 1 sehingga area dan malignant memiliki hubungan yang erat dalam keterkaitannya. 